/* Local-first, no-build Portfolio Studio workspace */
(()=>{'use strict';
const S=window.Studio;if(!S)return;
const $=id=>document.getElementById(id),clone=v=>structuredClone(v);
const key='portfolio-studio-draft-v2';let undo=[],redo=[],previous=JSON.stringify(S.get()),timer=null,restoring=false;
const sections=[['home','Introduction'],['work','Projects'],['about','About and skills'],['resume','Experience and education'],['contact','Contact']];
const bytes=s=>new TextEncoder().encode(s);
function download(blob,name){const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function save(){try{localStorage.setItem(key,JSON.stringify({version:2,modified:new Date().toISOString(),data:S.get()}));$('draftState').textContent='✓ Draft saved locally';$('saveStatus').textContent='✓ Autosaved in this browser'}catch(e){$('draftState').textContent='⚠ Local storage is full or unavailable. Export a backup.';$('saveStatus').textContent='⚠ Export a backup to avoid data loss'}}
function changed(){if(restoring)return;const current=JSON.stringify(S.get());if(current===previous)return;undo.push(previous);if(undo.length>60)undo.shift();redo=[];previous=current;updateControls();clearTimeout(timer);timer=setTimeout(save,350);applySettings()}
function setModel(object){restoring=true;S.set(object);restoring=false;previous=JSON.stringify(S.get());applySettings();updateControls();clearTimeout(timer);timer=setTimeout(save,100)}
function updateControls(){$('undoAction').disabled=!undo.length;$('redoAction').disabled=!redo.length}
$('undoAction').onclick=()=>{if(!undo.length)return;redo.push(previous);setModel(JSON.parse(undo.pop()))};
$('redoAction').onclick=()=>{if(!redo.length)return;undo.push(previous);setModel(JSON.parse(redo.pop()))};
window.addEventListener('studio-changed',changed);
window.addEventListener('studio-model-replaced',()=>{applySettings();renderResume()});
const tool=$('studioTools');$('studioToggle').onclick=()=>{tool.hidden=!tool.hidden};$('hideTools').onclick=()=>tool.hidden=true;$('editFromTools').onclick=()=>$('editBtn').click();
function button(label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',action);return b}
function renderSections(){const holder=$('sectionList');holder.replaceChildren();const data=S.get(),hidden=data.hiddenSections||[],order=data.sectionOrder||sections.map(x=>x[0]);const listed=[...order.filter(id=>sections.some(x=>x[0]===id)),...sections.map(x=>x[0]).filter(id=>!order.includes(id))];listed.forEach((id,i)=>{const div=document.createElement('div');div.className='section-row';const check=document.createElement('input');check.type='checkbox';check.checked=!hidden.includes(id);check.setAttribute('aria-label','Show '+sections.find(x=>x[0]===id)[1]);check.onchange=()=>{const d=S.get();d.hiddenSections=check.checked?(d.hiddenSections||[]).filter(x=>x!==id):[...(d.hiddenSections||[]),id];S.set(d)};const name=document.createElement('span');name.textContent=sections.find(x=>x[0]===id)[1];div.append(check,name,button('↑',()=>move(id,-1)),button('↓',()=>move(id,1)));holder.append(div)});function move(id,step){const d=S.get(),arr=listed.slice(),i=arr.indexOf(id),j=i+step;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];d.sectionOrder=arr;S.set(d)}}
function applySettings(){const d=S.get();const hidden=d.hiddenSections||[];const order=d.sectionOrder||sections.map(x=>x[0]);const main=$('main');
// Reorder actual DOM nodes instead of flex items: retains .wrap sizing and full-bleed sections.
const ordered=[...order.filter(id=>sections.some(x=>x[0]===id)),...sections.map(x=>x[0]).filter(id=>!order.includes(id))];
ordered.forEach(id=>{const el=$(id);if(el){el.hidden=hidden.includes(id);main.appendChild(el)}});
const accent=d.accent||'';document.body.style.setProperty('--custom-accent',accent);if(accent)document.body.style.setProperty('--accent',accent);else document.body.style.removeProperty('--accent');document.body.style.setProperty('--radius',String(d.cornerRadius??20)+'px');$('seoDescription').value=d.seoDescription||'';$('cornerRadius').value=d.cornerRadius??20;$('accentColor').value=/^#[0-9a-fA-F]{6}$/.test(accent)?accent:'#537b67';renderSections()}
$('restoreSections').onclick=()=>{const d=S.get();d.hiddenSections=[];d.sectionOrder=sections.map(x=>x[0]);S.set(d)};
$('accentColor').oninput=e=>{const d=S.get();d.accent=e.target.value;S.set(d)};
$('cornerRadius').oninput=e=>{const d=S.get();d.cornerRadius=+e.target.value;S.set(d)};
$('seoDescription').onchange=e=>{const d=S.get();d.seoDescription=e.target.value.trim();S.set(d)};
$('devicePreview').onchange=e=>{document.body.dataset.device=e.target.value};
const allowedTypes=['image/png','image/jpeg','image/webp','image/gif','image/svg+xml','application/pdf'];
async function fileData(file){if(!allowedTypes.includes(file.type))throw Error('Unsupported file format');if(file.size>8*1024*1024)throw Error('File must be under 8 MB');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Read failed'));reader.readAsDataURL(file)})}
async function upload(field,file){if(!file)return;try{const data=await fileData(file);const d=S.get();d[field]=data;S.set(d);$('draftState').textContent='✓ '+file.name+' attached'}catch(err){alert(err.message)}}
$('portraitUpload').onchange=e=>upload('avatar',e.target.files[0]);$('cvUpload').onchange=e=>upload('resume',e.target.files[0]);
function renderResume(){const holder=$('visualResume');holder.replaceChildren();const model=S.get();for(const [key,keys,title] of [['experience',['role','company','period','description'],'Work experience'],['education',['degree','institution','period'],'Education']]){const heading=document.createElement('h4');heading.textContent=title;holder.append(heading);(Array.isArray(model[key])?model[key]:[]).forEach((item,i)=>{const card=document.createElement('fieldset');card.className='resume-edit';const legend=document.createElement('legend');legend.textContent=(key==='experience'?(item.role||'New position'):(item.degree||'New qualification'));card.append(legend);keys.forEach(k=>{const label=document.createElement('label');label.textContent=({role:'Job title / role',company:'Employer / organisation',degree:'Qualification / degree',institution:'School / institution',period:'Dates / period',description:'Responsibilities and achievements'}[k]||k);const inp=k==='description'?document.createElement('textarea'):document.createElement('input');inp.value=item[k]||'';inp.placeholder=({period:'e.g. Jan 2024 – Present',role:'e.g. Junior Designer',degree:'e.g. Diploma in Graphic Design',company:'e.g. Design Studio',institution:'e.g. University or college',description:'Describe what you accomplished'}[k]||'');inp.addEventListener('input',()=>{const d=S.get();d[key][i][k]=inp.value;S.setField(key,d[key]);if(k==='role'||k==='degree')legend.textContent=inp.value||'New entry'});label.append(inp);card.append(label)});const actions=document.createElement('div');actions.className='resume-actions';actions.append(button('↑',()=>move(-1)),button('↓',()=>move(1)),button('Remove',()=>{const d=S.get();d[key].splice(i,1);S.set(d)}));function move(delta){const d=S.get(),to=i+delta;if(to<0||to>=d[key].length)return;[d[key][i],d[key][to]]=[d[key][to],d[key][i]];S.set(d)}card.append(actions);holder.append(card)});holder.append(button('+ Add '+(key==='experience'?'experience':'education'),()=>{const d=S.get();d[key]=d[key]||[];d[key].push(Object.fromEntries(keys.map(k=>[k,''])));S.set(d)}))}}
$('editBtn').addEventListener('click',renderResume);
function addResumeEntry(kind){const d=S.get();d[kind]=Array.isArray(d[kind])?d[kind]:[];d[kind].push(kind==='experience'?{role:'',company:'',period:'',description:''}:{degree:'',institution:'',period:''});d.hiddenSections=(d.hiddenSections||[]).filter(id=>id!=='resume');S.set(d);openResumeEditor();}
function openResumeEditor(){if(!$('editor').open)$('editBtn').click();const panel=$('resumeEditorPanel');panel.open=true;renderResume();panel.scrollIntoView({block:'start'});}
$('quickExperience').onclick=()=>addResumeEntry('experience');
$('quickEducation').onclick=()=>addResumeEntry('education');
$('toolsAddExperience').onclick=()=>addResumeEntry('experience');
$('toolsAddEducation').onclick=()=>addResumeEntry('education');
$('toolsEditResume').onclick=openResumeEditor;
$('resumeShow').onclick=()=>{const d=S.get();d.hiddenSections=(d.hiddenSections||[]).filter(id=>id!=='resume');S.set(d);$('studioTools').hidden=true;$('resume').scrollIntoView({behavior:'smooth'});};
$('jumpResume').onclick=()=>{const d=S.get();if((d.hiddenSections||[]).includes('resume')){d.hiddenSections=d.hiddenSections.filter(x=>x!=='resume');S.set(d)}$('studioTools').hidden=true;$('resume').scrollIntoView({behavior:'smooth'});};
$('jumpProjects').onclick=()=>{$('studioTools').hidden=true;$('work').scrollIntoView({behavior:'smooth'});};

// Small dependency-free ZIP encoder, STORE method. All entries are ordinary ZIP files.
const crcTable=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let i=0;i<8;i++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0});
function crc32(buf){let c=0xffffffff;for(const byte of buf)c=crcTable[(c^byte)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function zip(files){const local=[],central=[];let offset=0;for(const [name,source] of files){const filename=bytes(name),payload=typeof source==='string'?bytes(source):source,crc=crc32(payload);const header=new Uint8Array(30+filename.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,payload.length,true);v.setUint32(22,payload.length,true);v.setUint16(26,filename.length,true);header.set(filename,30);local.push(header,payload);const cd=new Uint8Array(46+filename.length),cv=new DataView(cd.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,payload.length,true);cv.setUint32(24,payload.length,true);cv.setUint16(28,filename.length,true);cv.setUint32(42,offset,true);cd.set(filename,46);central.push(cd);offset+=header.length+payload.length}const cdLength=central.reduce((s,x)=>s+x.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,cdLength,true);ev.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/zip'})}
const staticPaths=['style.css','course-themes.css','motion.css','public.js','motion.js','.nojekyll','assets/architecture-model.svg','assets/architecture-civic.svg','assets/architecture-profile.svg','assets/portrait.svg','assets/architecture-house.svg','assets/cv-placeholder.txt','assets/architecture-plan.svg','assets/project.svg'];
function xmlSafe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function exportZip(){const btn=$('exportWebsite');btn.disabled=true;btn.textContent='Preparing ZIP…';try{const d=S.get();const files=[];for(const path of staticPaths){const resp=await fetch(path);if(!resp.ok)throw Error('Cannot read '+path+' (serve this builder over HTTP rather than file://)');files.push([path,new Uint8Array(await resp.arrayBuffer())])}
const doc=document.cloneNode(true);doc.querySelector('.studio-bar')?.remove();doc.querySelector('#editor')?.remove();doc.querySelector('#studioTools')?.remove();doc.querySelector('#publishPreviewDialog')?.remove();doc.querySelectorAll('script').forEach(el=>el.remove());doc.querySelector('link[rel="stylesheet"][href="studio.css"]')?.remove();const meta=doc.querySelector('meta[name="description"]');meta?.setAttribute('content',(d.seoDescription||d.tagline||'Portfolio').slice(0,260));const og=doc.createElement('meta');og.setAttribute('property','og:title');og.setAttribute('content',d.name+' — '+d.role);doc.head.append(og);const ogd=doc.createElement('meta');ogd.setAttribute('property','og:description');ogd.setAttribute('content',(d.seoDescription||d.tagline||'').slice(0,260));doc.head.append(ogd);doc.body.removeAttribute('data-device');const script=doc.createElement('script');script.setAttribute('src','data.js');doc.body.append(script);const runtime=doc.createElement('script');runtime.setAttribute('src','public.js');doc.body.append(runtime);const motion=doc.createElement('script');motion.setAttribute('src','motion.js');doc.body.append(motion);doc.head.querySelector('title').textContent=d.name+' — Portfolio';files.push(['index.html','<!doctype html>\n'+doc.documentElement.outerHTML]);files.push(['data.js','window.PORTFOLIO_DATA = '+JSON.stringify(d,null,2)+';\n']);files.push(['README.txt','Upload the contents of this ZIP to a static hosting service or GitHub Pages. No server is required.\n']);const fileName=(d.name||'portfolio').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'portfolio';download(zip(files),fileName+'-website.zip');$('draftState').textContent='✓ Website ZIP exported'}catch(err){alert('Export failed: '+err.message)}finally{btn.disabled=false;btn.textContent='↓ Download full website ZIP'}}
$('exportWebsite').onclick=exportZip;
$('exportBackup').onclick=()=>download(new Blob([JSON.stringify(S.get(),null,2)],{type:'application/json'}),'portfolio-backup.json');
$('githubHelp').onclick=()=>window.open('https://docs.github.com/en/pages/quickstart','_blank','noopener,noreferrer');
// v4: clickable content mapping. Editing happens in the real form, never through contenteditable HTML.
let selecting=false;
const targetMap={heroName:['name'],heroRole:['role'],tagline:['tagline'],location:['location'],availability:['availability'],aboutText:['about'],emailLink:['email'],avatar:['avatar'],cvLink:['resume']};
function openField(field){if(!$('editor').open)$('editBtn').click();const input=$('edit_'+field);if(input){input.scrollIntoView({block:'center'});input.focus();input.classList.add('direct-edit-target');setTimeout(()=>input.classList.remove('direct-edit-target'),1600)}}
function openSection(section){if(!$('editor').open)$('editBtn').click();const summary=section==='work'?'Projects':section==='resume'?'Experience & education':null;if(summary){const details=[...$('editor').querySelectorAll('details')].find(el=>el.querySelector('summary')?.textContent.includes(summary));if(details){details.open=true;details.scrollIntoView({block:'start'})}}else if(section==='about')openField('about');else if(section==='contact')openField('email');else openField('name')}
if($('clickEditMode'))$('clickEditMode').onclick=()=>{selecting=!selecting;document.body.classList.toggle('click-edit-enabled',selecting);$('clickEditMode').textContent='◎ Click to edit: '+(selecting?'On':'Off');$('clickEditMode').setAttribute('aria-pressed',String(selecting))};
$('main').addEventListener('click',e=>{if(!selecting)return;const node=e.target.closest('section');if(!node)return;e.preventDefault();e.stopPropagation();const field=e.target.closest('[id]');const mapped=field&&targetMap[field.id];if(mapped){openField(mapped[0]);return}const project=e.target.closest('.project');if(project){const i=[...$('projects').children].indexOf(project);if(!$('editor').open)$('editBtn').click();const container=$('editProjects');const projectDetails=container.querySelectorAll('.project-edit-details')[i];if(projectDetails){container.closest('details').open=true;projectDetails.open=true;projectDetails.scrollIntoView({block:'center'});projectDetails.querySelector('input,textarea')?.focus()}return}openSection(node.id)},true);
$('main').addEventListener('keydown',e=>{if(selecting&&(e.key==='Enter'||e.key===' ')&&e.target.matches('[data-click-edit]')){e.preventDefault();e.target.click()}});
// Block presets reuse the existing data schema, so old exports remain compatible.
$('addBlock').onclick=()=>{const preset=$('blockPreset').value;if(!preset)return;const d=S.get();if(['project','architecture'].includes(preset)){d.projects=d.projects||[];d.projects.push(preset==='architecture'?{title:'New architecture project',category:'Architecture · Case study',year:String(new Date().getFullYear()),site:'',studio:'',tools:'',process:'',description:'Project brief, design intent, challenges and outcomes.',image:'assets/architecture-civic.svg',gallery:[],link:''}:{title:'New project',category:'Case study',year:String(new Date().getFullYear()),description:'Project objective, your role, process and measurable outcome.',image:'assets/project.svg',gallery:[],link:''});d.hiddenSections=(d.hiddenSections||[]).filter(id=>id!=='work')}else if(preset==='experience'){d.experience=d.experience||[];d.experience.push({role:'New position',company:'',period:'',description:''});d.hiddenSections=(d.hiddenSections||[]).filter(id=>id!=='resume')}else if(preset==='education'){d.education=d.education||[];d.education.push({degree:'New qualification',institution:'',period:''});d.hiddenSections=(d.hiddenSections||[]).filter(id=>id!=='resume')}else if(preset==='skills'){d.skills=d.skills||[];d.skills.push('New skill');d.hiddenSections=(d.hiddenSections||[]).filter(id=>id!=='about')}S.set(d);$('blockPreset').value='';openSection(['project','architecture'].includes(preset)?'work':['experience','education'].includes(preset)?'resume':'about')};
// Explicit revision checkpoints are stored independently from the current autosave.
const historyKey='portfolio-studio-versions-v4';
function readVersions(){try{const a=JSON.parse(localStorage.getItem(historyKey)||'[]');return Array.isArray(a)?a:[]}catch{return []}}
function writeVersions(a){localStorage.setItem(historyKey,JSON.stringify(a.slice(-12)));renderVersions()}
function renderVersions(){const select=$('versionList');select.replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent='Choose a saved revision…';select.append(blank);readVersions().forEach(v=>{const opt=document.createElement('option');opt.value=v.id;opt.textContent=v.label+' — '+new Date(v.date).toLocaleString();select.append(opt)})}
$('saveVersion').onclick=()=>{const label=prompt('Name this revision (for example: Before portfolio redesign)');if(!label?.trim())return;try{const a=readVersions();a.push({id:crypto.randomUUID(),label:label.trim().slice(0,70),date:new Date().toISOString(),data:S.get()});writeVersions(a);$('draftState').textContent='✓ Revision saved'}catch{$('draftState').textContent='⚠ Not enough local storage for revision; download a backup'}};
$('restoreVersion').onclick=()=>{const v=readVersions().find(v=>v.id===$('versionList').value);if(!v)return;if(confirm('Restore '+v.label+'? Your current draft will be replaced.')){S.set(v.data);$('draftState').textContent='✓ Revision restored'}};
$('deleteVersion').onclick=()=>{const id=$('versionList').value;if(!id)return;if(confirm('Delete this saved revision?'))writeVersions(readVersions().filter(v=>v.id!==id))};renderVersions();
// Preview the visitor-only layout by cloning the public markup and loading only its renderer.
function cleanProductionDoc(d){const doc=document.cloneNode(true);doc.querySelector('.studio-bar')?.remove();doc.querySelector('#editor')?.remove();doc.querySelector('#studioTools')?.remove();doc.querySelector('#publishPreviewDialog')?.remove();doc.querySelectorAll('script').forEach(el=>el.remove());doc.querySelector('link[href="studio.css"]')?.remove();doc.body.removeAttribute('data-device');doc.body.classList.remove('click-edit-enabled');doc.querySelector('meta[name="description"]')?.setAttribute('content',(d.seoDescription||d.tagline||'Portfolio').slice(0,260));doc.querySelector('title').textContent=(d.name||'Portfolio')+' — Portfolio';return doc}
$('publicationPreview').onclick=()=>{const d=S.get(),doc=cleanProductionDoc(d),base=doc.createElement('base');base.href=location.href;doc.head.prepend(base);const script=doc.createElement('script');script.textContent='window.PORTFOLIO_DATA='+JSON.stringify(d).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')+';';doc.body.append(script);const renderer=doc.createElement('script');renderer.src=new URL('public.js',location.href).href;doc.body.append(renderer);const motion=doc.createElement('script');motion.src=new URL('motion.js',location.href).href;doc.body.append(motion);$('publicationFrame').srcdoc='<!doctype html>\n'+doc.documentElement.outerHTML;$('publishPreviewDialog').showModal()};
$('closePublishPreview').onclick=()=>{$('publishPreviewDialog').close();$('publicationFrame').srcdoc=''};
$('publishPreviewDevice').onchange=e=>$('publicationFrame').style.width=e.target.value;

try{const raw=localStorage.getItem(key);if(raw){const draft=JSON.parse(raw);if(draft.version===2&&draft.data&&typeof draft.data.name==='string'&&Array.isArray(draft.data.projects))setModel(draft.data);else $('draftState').textContent='Draft format unknown — defaults loaded'}else $('draftState').textContent='Ready — edits save automatically'}catch(err){$('draftState').textContent='Draft could not be recovered; export a backup'}
applySettings();renderResume();updateControls();
})();
